[repositories]
rugix-extra = { git = "https://github.com/rugix/rugix-extra.git", branch = "v0.8" }

[systems.nxp-imx91-frdm]
layer = "nxp-imx91-frdm"
architecture = "arm64"
target = "bsp"

[systems.arduino-portenta-x8]
layer = "arduino-portenta-x8"
architecture = "arm64"
target = "bsp"
